- src/main/java/com/cong/fishisland/datasource/BilibiliDataSource.java
- src/main/java/com/cong/fishisland/manager/DataSourceRegistry.java
- src/main/java/com/cong/fishisland/model/enums/HotDataKeyEnum.java
- src/test/java/com/cong/fishisland/service/BilibiliSearchTest.java
feat(datasource): 添加 Bilibili 数据源
> feat(datasource): 添加 Bilibili 数据源

- src/main/java/com/cong/fishisland/datasource/JueJinDataSource.java
- src/main/java/com/cong/fishisland/manager/DataSourceRegistry.java
- src/main/java/com/cong/fishisland/model/enums/HotDataKeyEnum.java
- src/test/java/com/cong/fishisland/service/SearchTest.java
feat(datasource): 添加掘金数据源
- 新增 JueJinDataSource 类实现掘金数据源的热帖获取
- 在 DataSourceRegistry 中注册掘金数据源- 更新 HotDataKeyEnum，添加 JUE_JIN 枚举项
- 增加掘金热帖搜索的单元测试
> feat(datasource): 添加掘金数据源

- pom.xml
- src/main/java/com/cong/fishisland/config/MinioConfig.java
- src/main/java/com/cong/fishisland/controller/FileController.java
- src/main/java/com/cong/fishisland/manager/MinioManager.java
- src/main/resources/application.yml
- src/test/java/com/cong/fishisland/service/FileTest.java
feat(file): 添加 MinIO 文件存储支持
- 在 application.yml 中添加 MinIO 配置项
- 新增 MinioManager 类实现 MinIO 文件上传、下载和预签名 URL 生成功能
- 在 FileController 中添加 MinIO 文件上传接口
- 新增 FileTest 类进行 MinIO 文件上传测试
- 在 pom.xml 中添加 minio 依赖
> feat(file): 添加 MinIO 文件存储支持

- pom.xml
- sql/create_table.sql
- src/main/java/com/cong/fishisland/controller/user/UserController.java
- src/main/java/com/cong/fishisland/manager/EmailManager.java
- src/main/java/com/cong/fishisland/model/dto/user/UserLoginRequest.java
- src/main/java/com/cong/fishisland/model/dto/user/UserRegisterRequest.java
- src/main/java/com/cong/fishisland/model/entity/user/User.java
- src/main/java/com/cong/fishisland/model/vo/user/LoginUserVO.java
- src/main/java/com/cong/fishisland/service/UserService.java
- src/main/java/com/cong/fishisland/service/impl/user/UserServiceImpl.java
- src/main/resources/application.yml
- src/main/resources/mapper/UserMapper.xml
feat(user): 添加用户邮箱注册和登录功能
- 在 User 模型中添加 email 字段
- 新增 EmailManager 服务类，用于发送验证码邮件
- 在 UserController 中添加邮箱注册和登录相关接口
- 在 UserService 中实现邮箱注册和登录相关逻辑
- 更新 UserMapper.xml，添加与 User 模型中新增字段的映射- 在 application.yml 中添加邮件配置
> feat(user): 添加用户邮箱注册和登录功能

- src/main/java/com/cong/fishisland/datasource/hostpost/SmzdmDataSource.java
- src/main/java/com/cong/fishisland/manager/DataSourceRegistry.java
- src/main/java/com/cong/fishisland/model/enums/HotDataKeyEnum.java
- src/test/java/com/cong/fishisland/service/SearchTest.java
feat(datasource): 添加什么值得买数据源
- 新增 SmzdmDataSource 类实现什么值得买数据源的抓取和处理
- 在 DataSourceRegistry 中注册什么值得买数据源
- 更新 HotDataKeyEnum 枚举，添加 SM_ZDM 项
- 增加什么值得买数据源的单元测试
> feat(datasource): 添加什么值得买数据源

- src/main/java/com/cong/fishisland/datasource/hostpost/ZhiBo8DataSource.java
- src/main/java/com/cong/fishisland/manager/DataSourceRegistry.java
- src/main/java/com/cong/fishisland/model/enums/HotDataKeyEnum.java
- src/test/java/com/cong/fishisland/service/SearchTest.java
feat(datasource): 添加直播吧数据源
- 在 DataSourceRegistry 中注册直播吧数据源
- 在 HotDataKeyEnum 中添加 ZHI_BO_8 枚举项
- 新增 ZhiBo8DataSource 类实现直播吧数据抓取
- 更新 SearchTest 类，增加直播吧数据测试方法
> feat(datasource): 添加直播吧数据源

- sql/create_table.sql
- src/main/java/com/cong/fishisland/controller/emoticon/EmoticonFavourController.java
- src/main/java/com/cong/fishisland/mapper/emoticon/EmoticonFavourMapper.java
- src/main/java/com/cong/fishisland/model/dto/user/UserQueryRequest.java
- src/main/java/com/cong/fishisland/model/entity/emoticon/EmoticonFavour.java
- src/main/java/com/cong/fishisland/service/EmoticonFavourService.java
- src/main/java/com/cong/fishisland/service/impl/emoticon/EmoticonFavourServiceImpl.java
- src/main/java/com/cong/fishisland/service/impl/user/UserServiceImpl.java
- src/main/resources/mapper/EmoticonFavourMapper.xml
后端项目 新增收藏表情包接口
修复管理员通过账号查询不到用户问题
> 2025-04-02 新增收藏表情包接口 修复管理员通过账号查询不到用户问题

- src/main/java/com/cong/fishisland/controller/user/UserController.java
- src/main/java/com/cong/fishisland/manager/EmailManager.java
- src/main/java/com/cong/fishisland/model/dto/user/UserBindEmailRequest.java
- src/main/java/com/cong/fishisland/model/dto/user/UserEmailResetPasswordRequest.java
- src/main/java/com/cong/fishisland/service/UserService.java
- src/main/java/com/cong/fishisland/service/impl/user/UserServiceImpl.java
> Shing dev -- 添加用户邮箱绑定和找回密码功能

- pom.xml
- sql/create_table.sql
- src/main/java/com/cong/fishisland/cache/AuthStateRedisCache.java
- src/main/java/com/cong/fishisland/config/GiteeConfig.java
- src/main/java/com/cong/fishisland/constant/Oauth2Constant.java
- src/main/java/com/cong/fishisland/controller/user/RestAuthController.java
- src/main/java/com/cong/fishisland/mapper/user/UserThirdAuthMapper.java
- src/main/java/com/cong/fishisland/model/entity/user/UserThirdAuth.java
- src/main/java/com/cong/fishisland/model/vo/user/LoginUserVO.java
- src/main/java/com/cong/fishisland/model/vo/user/PlatformBindVO.java
- src/main/java/com/cong/fishisland/service/UserThirdAuthService.java
- src/main/java/com/cong/fishisland/service/impl/user/UserServiceImpl.java
- src/main/java/com/cong/fishisland/service/impl/user/UserThirdAuthServiceImpl.java
- src/main/resources/application-dev.yml
- src/main/resources/mapper/UserThirdAuthMapper.xml
> feat: ✨ 添加Github和Gitee的三方登录以及绑定

- src/main/java/com/cong/fishisland/manager/EmailManager.java
- src/main/java/com/cong/fishisland/service/impl/user/UserServiceImpl.java
- 将验证码有效期从 1 分钟调整为 5 分钟
- 优化验证码验证逻辑，区分验证码为空、已过期和错误的情况
> perf(email): 优化邮箱验证码

- sql/create_table.sql
- src/main/java/com/cong/fishisland/controller/donation/DonationRecordsController.java
- src/main/java/com/cong/fishisland/mapper/donation/DonationRecordsMapper.java
- src/main/java/com/cong/fishisland/model/dto/donation/DonationRecordsAddRequest.java
- src/main/java/com/cong/fishisland/model/dto/donation/DonationRecordsEditRequest.java
- src/main/java/com/cong/fishisland/model/dto/donation/DonationRecordsQueryRequest.java
- src/main/java/com/cong/fishisland/model/dto/donation/DonationRecordsUpdateRequest.java
- src/main/java/com/cong/fishisland/model/entity/donation/DonationRecords.java
- src/main/java/com/cong/fishisland/model/vo/donation/DonationRecordsVO.java
- src/main/java/com/cong/fishisland/service/DonationRecordsService.java
- src/main/java/com/cong/fishisland/service/impl/donation/DonationRecordsServiceImpl.java
- src/main/resources/mapper/DonationRecordsMapper.xml
- src/test/java/com/cong/fishisland/service/DonationRecordsServiceTest.java
- 新增用户打赏记录表和相关实体类
- 实现打赏记录的增删改查接口
- 添加打赏记录的分页查询功能- 优化打赏逻辑，支持累加金额和更新备注
- 增加并发控制，确保打赏金额的准确性
> feat(donation): 添加用户打赏记录功能

- sql/create_table.sql
- src/main/java/com/cong/fishisland/mapper/user/EmailBanMapper.java
- src/main/java/com/cong/fishisland/model/entity/user/EmailBan.java
- src/main/java/com/cong/fishisland/service/EmailBanService.java
- src/main/java/com/cong/fishisland/service/impl/user/EmailBanServiceImpl.java
- src/main/java/com/cong/fishisland/service/impl/user/UserServiceImpl.java
- src/main/resources/mapper/EmailBanMapper.xml
> feat(user): 增加邮箱封禁功能并优化邮箱验证逻辑

- src/main/java/com/cong/fishisland/constant/RedisKey.java
- src/main/java/com/cong/fishisland/controller/hero/HeroController.java
- src/main/java/com/cong/fishisland/model/vo/hero/HeroVO.java
- src/main/java/com/cong/fishisland/service/impl/HeroServiceImpl.java
- src/main/java/com/cong/fishisland/utils/CryptoUtils.java
- 新增英雄随机获取和猜谜记录功能
- 优化英雄数据传输加密
- 调整英雄ID为字符串类型
- 增加用户当前英雄记录的Redis缓存
> feat(hero): 添加英雄猜谜功能并优化相关服务

- src/main/java/com/cong/fishisland/service/impl/user/UserServiceImpl.java
- 在方法开头添加判断，如果未登录则直接返回 null
- 这样可以减少不必要的 session 访问，提高性能
> perf(user): 优化 getLoginUserPermitNull 方法

- src/main/java/com/cong/fishisland/controller/hero/HeroController.java
- src/main/java/com/cong/fishisland/utils/CryptoUtils.java
- 新增 CryptoUtils 加密工具类，提供安全加密和解密方法
- 修改 HeroController 中的 getRandomHero 方法，返回加密后的英雄数据
- 使用 JSON 序列化英雄对象，然后进行加密处理
> feat(hero): 加密随机英雄接口返回数据

- src/main/java/com/cong/fishisland/constant/NewUserDataTypeWebConstant.java
- src/main/java/com/cong/fishisland/constant/RedisKey.java
- src/main/java/com/cong/fishisland/controller/user/UserController.java
- src/main/java/com/cong/fishisland/mapper/user/UserMapper.java
- src/main/java/com/cong/fishisland/model/dto/user/NewUserDataWebRequest.java
- src/main/java/com/cong/fishisland/model/enums/DeleteStatusEnum.java
- src/main/java/com/cong/fishisland/model/vo/user/NewUserDataWebVO.java
- src/main/java/com/cong/fishisland/model/vo/user/UserDataWebVO.java
- src/main/java/com/cong/fishisland/service/UserService.java
- src/main/java/com/cong/fishisland/service/impl/emoticon/EmoticonFavourServiceImpl.java
- src/main/java/com/cong/fishisland/service/impl/user/UserServiceImpl.java
- src/main/resources/mapper/UserMapper.xml
- 使用 Redis 实现表情包收藏的防抖功能
- 新增 RedisKey.EMOTICON_FAVOUR_DEBOUNCE 常量用于防抖键
- 在收藏表情包时增加防抖校验，避免用户频繁操作
> feat(emoticon): 添加表情包收藏防抖功能

- src/main/java/com/cong/fishisland/constant/PointConstant.java
- src/main/java/com/cong/fishisland/constant/RedisKey.java
- src/main/java/com/cong/fishisland/controller/user/UserController.java
- src/main/java/com/cong/fishisland/service/UserPointsService.java
- src/main/java/com/cong/fishisland/service/impl/user/UserPointsServiceImpl.java
- 新增用户改名限制和防抖相关常量
- 在用户信息更新接口中添加改名限制和防抖逻辑
- 新增扣除积分方法并用于用户改名操作
- 添加事务支持以确保数据一致性
> feat(user): 用户改名功能与防抖机制

- src/main/java/com/cong/fishisland/controller/user/UserController.java
- 在更新用户信息前增加非空校验，避免不必要的更新操作
- 仅当用户昵称、头像或个人简介有变化时才执行更新- 优化代码结构，提高代码的可读性和性能
> refactor(user): 优化用户信息更新逻辑

- src/main/java/com/cong/fishisland/controller/user/UserController.java
- src/main/java/com/cong/fishisland/model/dto/user/UserQueryRequest.java
- src/main/java/com/cong/fishisland/model/vo/user/UserDataWebVO.java
- src/main/java/com/cong/fishisland/service/impl/user/UserServiceImpl.java
- src/main/resources/mapper/UserMapper.xml
- 新增防抖逻辑，防止频繁更新用户资料
- 修改用户名逻辑，允许管理员修改用户名
> feat(user): 优化用户修改资料逻辑，增加管理员权限支持

- pom.xml
- src/main/java/com/cong/fishisland/datasource/hostpost/QQMusicDataSource.java
> feat:聚合QQ音乐数据源

- sql/create_table.sql
- src/main/java/com/cong/fishisland/controller/comment/CommentController.java
- src/main/java/com/cong/fishisland/model/dto/comment/ChildCommentQueryRequest.java
- src/main/java/com/cong/fishisland/model/dto/comment/CommentAddRequest.java
- src/main/java/com/cong/fishisland/model/entity/comment/Comment.java
- src/main/java/com/cong/fishisland/service/impl/comment/CommentServiceImpl.java
- src/main/resources/mapper/CommentMapper.xml
- 在 Comment 模型中添加 rootId 字段，用于标识根评论
- 更新 CommentAddRequest 和 ChildCommentQueryRequest DTO，增加 rootId 相关字段和逻辑
- 修改 CommentController 和 CommentServiceImpl 中的相关方法，支持根评论ID的处理
- 更新数据库表结构，在 comment 表中添加 rootId 列
- 调整 CommentMapper.xml 中的 SQL 语句，包含新添加的 rootId 字段
> 添加根评论ID字段并更新相关功能

- sql/create_table.sql
- src/main/java/com/cong/fishisland/config/AsyncConfig.java
- src/main/java/com/cong/fishisland/constant/ActionTypeConstant.java
- src/main/java/com/cong/fishisland/constant/SourceTypeConstant.java
- src/main/java/com/cong/fishisland/controller/comment/CommentController.java
- src/main/java/com/cong/fishisland/controller/event/EventRemindController.java
- src/main/java/com/cong/fishisland/mapper/event/EventRemindMapper.java
- src/main/java/com/cong/fishisland/model/dto/event/EventRemindQueryRequest.java
- src/main/java/com/cong/fishisland/model/dto/event/EventRemindStateRequest.java
- src/main/java/com/cong/fishisland/model/entity/event/EventRemind.java
- src/main/java/com/cong/fishisland/model/vo/event/EventRemindVO.java
- src/main/java/com/cong/fishisland/service/EventRemindService.java
- src/main/java/com/cong/fishisland/service/event/EventRemindHandler.java
- src/main/java/com/cong/fishisland/service/impl/comment/CommentServiceImpl.java
- src/main/java/com/cong/fishisland/service/impl/comment/CommentThumbServiceImpl.java
- src/main/java/com/cong/fishisland/service/impl/event/EventRemindServiceImpl.java
- src/main/java/com/cong/fishisland/service/impl/post/PostThumbServiceImpl.java
- src/main/resources/mapper/EventRemindMapper.xml
- 实现评论、点赞等操作的事件提醒逻辑- 添加事件提醒的批量读取和查询功能
- 优化了数据库表结构，增加了索引
> feat(event): 添加事件提醒功能- 新增事件提醒相关的数据结构和接口

- src/main/java/com/cong/fishisland/controller/post/PostController.java
- src/main/java/com/cong/fishisland/service/PostService.java
- src/main/java/com/cong/fishisland/service/impl/post/PostServiceImpl.java
- 在 PostController 中添加分页获取当前用户收藏的帖子接口
- 在 PostService 接口中添加相应的方法声明
- 在 PostServiceImpl 中实现分页查询用户收藏的帖子功能
- 优化 PostServiceImpl 中的帖子查询逻辑，增加评论数字段
> feat(post): 添加我的收藏帖子功能
